insert into public.places (id, name, kind, neighborhood, lng, lat, rating, hours, specialty, photo, description, meal, source_url, last_verified_on) values
-- Record stores
('mm', 'Music Millennium', 'record', 'Buckman / Kerns', -122.6319444, 45.5227167, 4.7, 'Mon–Sat 10 AM–10 PM · Sun 11 AM–9 PM', 'New releases · Massive all-format stock', '🎧', 'Portland''s longest-running record shop — vinyl, CDs, and cassettes across two floors, plus a deep local-artist wall.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJYasibsCglVQR2CKwN4o4b18', current_date),
('lr', 'Little Axe Records', 'record', 'Hollywood District', -122.62061, 45.5356651, 4.9, 'Daily 12–7 PM', 'Curated genre bins · Deep cassette stock', '💿', 'Small, sharply curated shop on NE Sandy — alphabetized bins and an unusually deep cassette selection.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJyWX5Xd6mlVQRQhpGpE5LJAk', current_date),
('ec', 'Everyday Music', 'record', 'Nob Hill / Pearl District', -122.6848042, 45.5230092, 4.5, 'Daily 11 AM–8 PM', 'Used vinyl · CDs · Film', '📀', 'High-volume used-media stop on West Burnside; patient digging turns up serious deals.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJT5Pv5AIKlVQRhy-J5-Ccxfo', current_date),
('mr', 'Mississippi Records', 'record', 'Boise-Eliot', -122.6747752, 45.5605325, 4.8, 'Daily 12–7 PM', 'Folk · Blues · Global', '🪕', 'Beautifully curated records, reissues, and esoteric gems on N Albina, a block off Mississippi Ave.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJN0v2B2unlVQRlZ0fylFx89o', current_date),
('jr', 'Jackpot Records', 'record', 'Hawthorne', -122.6271854, 45.511937, 4.5, 'Mon–Thu 11–6 · Fri–Sat 11–7 · Sun 11–5', 'New & used · Listening stations', '🎵', 'Hawthorne institution with a strong new-release wall and a turntable up front to test before you buy.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJ9Sfq942glVQRDH4TmL4CpnY', current_date),
('av2', '2nd Avenue Records', 'record', 'Downtown', -122.6726267, 45.5218858, 4.7, 'Daily 12–5 PM', 'Punk · Metal · Vintage tees', '🎸', 'Downtown staple known for its punk and metal depth, band tees, and a welcoming vibe for local musicians.', null, 'https://www.google.com/maps/place/?q=place_id:ChIJKRqFbgYKlVQR2KaAfCfMNTs', current_date),

-- Food, each verified within 2 miles of the record store it's paired with
('lu', 'Luc Lac Vietnamese Kitchen', 'food', 'Downtown', -122.6754165, 45.5168971, 4.4, 'Daily 11 AM–2:30 PM · 4–11 PM', 'Vietnamese · Late-night', '🍜', 'Fast Vietnamese comfort food downtown — in range of both Everyday Music and 2nd Avenue Records.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJpTJKdg8KlVQRo08EmCpdcaQ', current_date),
('jo', 'Janken', 'food', 'Pearl District', -122.6841156, 45.5249173, 4.3, 'Tue–Thu, Sun 5–10 PM · Fri–Sat 5–11 PM', 'Japanese · Upscale shareables', '🍣', '0.1 mi from Everyday Music — polished Japanese small plates and sushi, good for a splurge dinner.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJbXdpPPgLlVQRv2mZs1NygTA', current_date),
('sde', 'Screen Door Eastside', 'food', 'Kerns', -122.641625, 45.523017, 4.7, 'Daily 8:30 AM–2 PM · 4:30–9:30 PM', 'Southern comfort · Fried chicken', '🍗', '0.5 mi from Music Millennium — Southern brunch and fried chicken in a lively room.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJu1MQrL6glVQRNuGYoTmvBoY', current_date),
('aoa', 'Ate-Oh-Ate', 'food', 'Kerns', -122.640256, 45.522656, 4.5, 'Daily 11 AM–9 PM', 'Hawaiian plate lunch', '🍱', 'Plate-lunch Hawaiian food a few blocks from Music Millennium.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJZUIJub6glVQR9UV3rm3ElOo', current_date),
('hv', 'Hearth & Vine', 'food', 'Pearl District', -122.6829435, 45.523303, 4.6, 'Tue–Sun 11 AM–10 PM', 'Wine bar · New American', '🍷', 'Steps from Everyday Music — wine-forward New American with a terrace.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJ6fJ7btQLlVQRHpt4Vxd3pL4', current_date),
('dns', 'Ding & Spice', 'food', 'Hawthorne', -122.6285016, 45.5118576, 4.6, 'Daily 11 AM–9/10 PM', 'Szechuan · Hand-pulled noodles', '🌶️', 'A block from Jackpot Records — modern Szechuan with mala and dan dan noodles.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJuxWplZyhlVQRM_tEpgh4oWg', current_date),
('nh', 'Naan Hero', 'food', 'Hawthorne', -122.6324815, 45.5122375, 4.8, 'Wed–Sun 11 AM–6 PM', 'NYC-style naan sandwiches', '🥙', 'A cart near Jackpot Records turning naan into NYC bodega-style sandwiches.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJp-j-DwChlVQR4LwMm5ee0BI', current_date),
('shu', 'Shucos PDX', 'food', 'Hollywood District', -122.6217559, 45.5355634, 4.8, 'Daily 12–9:30 PM', 'Guatemalan hot dogs · Churrasco', '🌭', 'House-made Guatemalan sausages right by Little Axe Records.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJTzrz6gahlVQRGeDGFL2Hqpo', current_date),
('cmk', 'Cappadocia Mediterranean Kitchen', 'food', 'Hollywood District', -122.6217388, 45.535771, 4.9, 'Mon 9–5 · Tue–Sun 11–9', 'Turkish · Pide · Kebab', '🫓', 'Handmade pide and kebab a few doors from Little Axe Records.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJdcDWTAKhlVQRuv7ncezzKa8', current_date),
('psm', 'Pine Street Market', 'food', 'Downtown', -122.6723426, 45.5213258, 4.6, 'Daily 11 AM–9 PM', 'Food hall · Multiple vendors', '🍽️', 'Historic food hall a block from 2nd Avenue Records — good for splitting a group.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJV7s9_gYKlVQRXW_qfoK0U-A', current_date),
('xdd', 'Xin Ding Dumpling House', 'food', 'Downtown', -122.6724998, 45.5222443, 4.6, 'Mon–Thu 11–2:30, 4–9 · Fri–Sat 11–1 AM · Sun 11–9', 'Dumplings · Sichuan', '🥟', 'Dumplings and Sichuan classics next door to 2nd Avenue Records.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJk7-rmcELlVQR9xTHsXlAxYE', current_date),
('lf', 'Lovely''s Fifty Fifty', 'food', 'Boise-Eliot', -122.6758503, 45.5528597, 4.7, 'Daily 5–10 PM', 'Neapolitan pizza · House ice cream', '🍕', 'Half a mile from Mississippi Records — wood-fired pizza on N Mississippi Ave.', 'Dinner', 'https://www.google.com/maps/place/?q=place_id:ChIJT9ZbCWunlVQRIryTTXOWkEw', current_date),
('mt', 'Meesen Thai Eatery', 'food', 'Boise-Eliot', -122.675204, 45.551243, 4.5, 'Daily 11:30 AM–10 PM', 'Thai · Boat noodles', '🍲', 'Casual Thai lunch spot two-thirds of a mile from Mississippi Records.', 'Lunch', 'https://www.google.com/maps/place/?q=place_id:ChIJrcFxT2qnlVQRYw8-d773WFc', current_date)
on conflict (id) do update set
  name = excluded.name, kind = excluded.kind, neighborhood = excluded.neighborhood, lng = excluded.lng, lat = excluded.lat,
  rating = excluded.rating, hours = excluded.hours, specialty = excluded.specialty, photo = excluded.photo,
  description = excluded.description, meal = excluded.meal, source_url = excluded.source_url, last_verified_on = excluded.last_verified_on;
