-- Restaurants are out of scope now; keep the catalog to record stores only.
delete from public.places where kind = 'food';

insert into public.places (id, name, kind, neighborhood, lng, lat, rating, hours, specialty, photo, description, meal, image, last_verified_on) values
('mm', 'Music Millennium', 'record', 'Kerns', -122.6319444, 45.5227167, 4.7, 'Open daily · Closes 9–10 PM', 'New releases · Local artists', '🎧', 'An all-purpose Portland institution with deep new-vinyl bins and an excellent local music wall.', null, null, current_date),
('lr', 'Little Axe Records', 'record', 'Hollywood District', -122.62061, 45.5356651, 4.9, 'Open daily · Closes 7 PM', 'Soul · Jazz · Rare groove', '💿', 'Small, selective shop for adventurous digging: private press, international funk, and heavyweight jazz.', null, null, current_date),
('ec', 'Everyday Music', 'record', 'Pearl District', -122.6848042, 45.5230092, 4.5, 'Open daily · Closes 8 PM', 'Used vinyl · CDs · Books', '📀', 'A high-volume used-media stop where patient crate digging pays off.', null, null, current_date),
('mr', 'Mississippi Records', 'record', 'Boise', -122.6747752, 45.5605325, 4.8, 'Open daily · Closes 7 PM', 'Folk · Blues · Global', '🪕', 'Beautifully curated records, reissues, and esoteric gems from around the world.', null, null, current_date),
('av', '2nd Avenue Records', 'record', 'Downtown', -122.6726267, 45.5218858, 4.7, 'Open daily · Closes 5 PM', 'Punk · Metal · Used vinyl', '🎸', 'A downtown staple with deep punk, metal, and used-vinyl bins, run by people who clearly love the format.', null, null, current_date),
('jp', 'Jackpot Records', 'record', 'Hawthorne', -122.6271854, 45.511937, 4.5, 'Open daily · Closes 5–7 PM', 'New releases · Reissues', '🎻', 'A Hawthorne favorite for new releases and reissues, with a listening station to test records before you buy.', null, null, current_date),
('sc', 'Second Chance Records', 'record', 'Montavilla', -122.6043195, 45.5227151, 5.0, 'Thu–Sun · Closes 8 PM', 'Used vinyl · All genres', '📻', 'A cozy, welcoming shop with a wide-ranging genre mix, records cleaned and resleeved before they hit the racks.', null, null, current_date),
('vu', 'My Vinyl Underground', 'record', 'Division-Clinton', -122.6516711, 45.5049835, 4.9, 'Fri–Sun · Closes 6 PM', 'Basement digs · Rarities', '🎷', 'A basement hideaway off Division with fairly priced rarities and handwritten notes on the harder-to-find stuff.', null, null, current_date),
('tm', 'Too Many Records', 'record', 'St. Johns', -122.6857368, 45.5768356, 4.9, 'Tue–Sun · Closes 8 PM', 'Curated used vinyl', '🎺', 'A consciously curated used-vinyl shop in St. Johns with a constantly rotating, well-graded selection.', null, null, current_date),
('vr', 'Vinyl Resting Place', 'record', 'St. Johns', -122.7527576, 45.5893692, 4.7, 'Thu–Sun · Closes 5 PM', 'New & used · $1 bins', '🎹', 'A St. Johns gem with deep new-and-used stock and bargain $1 bins worth digging through.', null, null, current_date),
('cm', 'Crossroads Music', 'record', 'Foster-Powell', -122.5797858, 45.4828406, 4.7, 'Open daily · Closes 6–7 PM', 'Vinyl · CDs · Cassettes', '🎶', 'A big, eclectic media stop in outer Southeast with vinyl, CDs, and one of the better cassette selections in town.', null, null, current_date),
('lf', 'Landfill Rescue Unit Records', 'record', 'Buckman', -122.6393733, 45.5166465, 4.7, 'Open daily · Closes 7 PM', 'Punk · Metal · Esoteric', '🤘', 'A Buckman favorite for punk, metal, and harder-to-find records, with labeled genres and a listening station.', null, null, current_date),
('rp', 'The Record Pub', 'record', 'Sellwood', -122.6491491, 45.4787278, 4.9, 'Open daily · Closes 7–10 PM', 'Rock vinyl · Record bar', '🍺', 'Part record shop, part bar -- browse rock vinyl in Sellwood''s Iron Horse building with a pint in hand.', null, null, current_date),
('dv', 'Dig Vinyl', 'record', 'Sellwood-Westmoreland', -122.6531767, 45.4630689, 4.9, 'Open daily · Closes 7 PM', 'Jazz · Rock · Hole-in-the-wall', '🕵️', 'A tiny Sellwood hole-in-the-wall with a well-priced, well-graded selection especially strong in jazz and rock.', null, null, current_date),
('va', 'Variety Records', 'record', 'Foster-Powell', -122.6116982, 45.4971926, 4.7, 'Open daily · Closes 5 PM', 'Vinyl · CDs · DVDs', '📼', 'A Foster Road media shop stacked with vinyl, CDs, DVDs, and cassettes at low prices.', null, null, current_date),
('ex', 'Exiled Records', 'record', 'Beaverton', -122.7666471, 45.498266, 4.7, 'Open daily · Closes 6–8 PM', 'Pop · Rock · Hip-hop', '🔊', 'A big Beaverton-area shop with deep pop, rock, and hip-hop bins plus a solid clearance section.', null, null, current_date),
('cn', 'City Noise Records', 'record', 'Montavilla', -122.5906726, 45.5267087, 4.9, 'Wed–Sun · Closes 6 PM', 'Punk · Hardcore · DIY', '🎙️', 'An old-school punk and hardcore shop attached to a cafe in Montavilla, with a tight, hand-picked selection.', null, null, current_date),
('bs', 'B-Side Records & Vintage', 'record', 'Milwaukie', -122.6417095, 45.4446209, 4.8, 'Open daily · Closes 5–9 PM', 'Vinyl · Antiques · Live music', '🕰️', 'A downtown Milwaukie record-and-antiques shop with a small bar and regular live performances.', null, null, current_date),
('dr', 'Daily Records', 'record', 'Oak Grove', -122.6235654, 45.4071832, 4.9, 'Tue–Sun · Closes 5–6 PM', 'New & used · Turntable gear', '🎵', 'A low-key Oak Grove shop with new and used vinyl plus turntable gear and cleaning supplies.', null, null, current_date),
('r503', '503 Records', 'record', 'Beaverton', -122.8066143, 45.4920266, 4.9, 'Wed–Sun · Closes 5–8 PM', 'Hip-hop · All genres', '🎤', 'A small Beaverton shop known for its hip-hop selection and a genuinely welcoming owner.', null, null, current_date),
('bw', 'Black Water Records', 'record', 'Hollywood District', -122.6105869, 45.5401251, 4.7, 'Open daily · Closes 7 PM', 'Punk · Goth · Industrial', '🖤', 'An all-volunteer, punk-community shop on NE Sandy with deep goth, industrial, and hardcore stock.', null, null, current_date),
('r1709', '1709 Records', 'record', 'Vancouver, WA', -122.670238, 45.634447, 4.8, 'Wed–Sun · Closes 5 PM', 'New & used · Metal · Punk', '🐕', 'A cozy, dog-friendly Vancouver, WA shop with a strong punk and metal selection.', null, null, current_date),
('eb', 'Everybody''s Music', 'record', 'Vancouver, WA', -122.6676545, 45.6350898, 4.7, 'Wed–Sun · Closes 6–7 PM', 'Used vinyl · DVDs · Blu-ray', '🎞️', 'A well-organized Vancouver, WA shop with deep used vinyl, CDs, and a well-loved dollar section.', null, null, current_date),
('rr', 'Ronald Records', 'record', 'Vancouver, WA', -122.6714488, 45.6290568, 4.8, 'Open daily · Closes 6 PM', 'Community hub · All genres', '🎉', 'A Vancouver, WA record shop that doubles as a community hub, with regular listening parties.', null, null, current_date)
on conflict (id) do update set
  name = excluded.name, neighborhood = excluded.neighborhood, lng = excluded.lng, lat = excluded.lat,
  rating = excluded.rating, hours = excluded.hours, specialty = excluded.specialty, photo = excluded.photo,
  description = excluded.description, meal = excluded.meal, last_verified_on = excluded.last_verified_on;
