alter table public.places add column if not exists image text;

insert into public.places (id, name, kind, neighborhood, lng, lat, rating, hours, specialty, photo, description, meal, image, last_verified_on) values
('mm', 'Music Millennium', 'record', 'Kerns', -122.6319444, 45.5227167, 4.7, 'Open daily · Closes 9–10 PM', 'New releases · Local artists', '🎧', 'An all-purpose Portland institution with deep new-vinyl bins and an excellent local music wall.', null, null, current_date),
('lr', 'Little Axe Records', 'record', 'Hollywood District', -122.62061, 45.5356651, 4.9, 'Open daily · Closes 7 PM', 'Soul · Jazz · Rare groove', '💿', 'Small, selective shop for adventurous digging: private press, international funk, and heavyweight jazz.', null, null, current_date),
('ec', 'Everyday Music', 'record', 'Pearl District', -122.6848042, 45.5230092, 4.5, 'Open daily · Closes 8 PM', 'Used vinyl · CDs · Books', '📀', 'A high-volume used-media stop where patient crate digging pays off.', null, null, current_date),
('mr', 'Mississippi Records', 'record', 'Boise', -122.6747752, 45.5605325, 4.8, 'Open daily · Closes 7 PM', 'Folk · Blues · Global', '🪕', 'Beautifully curated records, reissues, and esoteric gems from around the world.', null, null, current_date),
('av', '2nd Avenue Records', 'record', 'Downtown', -122.6726267, 45.5218858, 4.7, 'Open daily · Closes 5 PM', 'Punk · Metal · Used vinyl', '🎸', 'A downtown staple with deep punk, metal, and used-vinyl bins, run by people who clearly love the format.', null, null, current_date),
('jp', 'Jackpot Records', 'record', 'Hawthorne', -122.6271854, 45.511937, 4.5, 'Open daily · Closes 5–7 PM', 'New releases · Reissues', '🎻', 'A Hawthorne favorite for new releases and reissues, with a listening station to test records before you buy.', null, null, current_date),
('sc', 'Second Chance Records', 'record', 'Montavilla', -122.6043195, 45.5227151, 5.0, 'Thu–Sun · Closes 8 PM', 'Used vinyl · All genres', '📻', 'A cozy, welcoming shop with a wide-ranging genre mix, records cleaned and resleeved before they hit the racks.', null, null, current_date),
('vu', 'My Vinyl Underground', 'record', 'Division-Clinton', -122.6516711, 45.5049835, 4.9, 'Fri–Sun · Closes 6 PM', 'Basement digs · Rarities', '🎷', 'A basement hideaway off Division with fairly priced rarities and handwritten notes on the harder-to-find stuff.', null, null, current_date),
('tm', 'Too Many Records', 'record', 'St. Johns', -122.6857368, 45.5768356, 4.9, 'Tue–Sun · Closes 8 PM', 'Curated used vinyl', '🎺', 'A consciously curated used-vinyl shop in St. Johns with a constantly rotating, well-graded selection.', null, null, current_date),
('vr', 'Vinyl Resting Place', 'record', 'St. Johns', -122.7527576, 45.5893692, 4.7, 'Thu–Sun · Closes 5 PM', 'New & used · $1 bins', '🎹', 'A St. Johns gem with deep new-and-used stock and bargain $1 bins worth digging through.', null, null, current_date),
('lu', 'Lúc Lác', 'food', 'Downtown', -122.6754165, 45.5168971, 4.4, 'Open daily · Closes 11 PM', 'Vietnamese · Casual', '🍜', 'Fast Vietnamese comfort food; great for an easy midday reset.', 'Lunch', null, current_date),
('jo', 'Janken', 'food', 'Pearl District', -122.6841156, 45.5249173, 4.3, 'Dinner Tue–Sun from 5 PM', 'Japanese · Sushi', '🍣', 'An upscale Japanese spot in the Pearl with sushi, caviar, and a polished dinner-only menu.', 'Dinner', null, current_date),
('fk', 'Farmhouse Kitchen Thai Cuisine', 'food', 'Hawthorne', -122.6297626, 45.5118791, 4.7, 'Lunch & dinner daily', 'Thai · Noodles', '🍲', 'A lively Thai spot on Hawthorne known for hat yai chicken and rich noodle soups.', 'Lunch', null, current_date),
('ts', 'Tin Shed Garden Cafe', 'food', 'Alberta Arts District', -122.6508762, 45.558964, 4.6, 'Breakfast & lunch · Closes 2–3 PM', 'Brunch · Comfort food', '🥞', 'A neighborhood Alberta brunch spot with hearty, vegetarian-friendly comfort food.', 'Lunch', null, current_date),
('ur', 'Urdaneta', 'food', 'Alberta Arts District', -122.6340327, 45.5591185, 4.8, 'Dinner Tue–Sun from 5 PM', 'Basque · Tapas', '🥘', 'An upscale Basque pintxos and tapas spot on Alberta, best saved for a special dinner.', 'Dinner', null, current_date),
('ta', 'Tartuca', 'food', 'Mississippi District', -122.6757973, 45.5515759, 4.6, 'Dinner Tue–Sun from 4:30 PM', 'Italian · Handmade pasta', '🍝', 'A cozy Italian spot on Mississippi Ave with handmade pasta and great focaccia.', 'Dinner', null, current_date),
('pq', '¿Por Qué No?', 'food', 'Mississippi District', -122.6753254, 45.5481556, 4.6, 'Open daily · Closes 9:30–10 PM', 'Mexican · Tacos', '🌮', 'A colorful, casual Mexican spot on Mississippi Ave with reliably good tacos and salsas.', 'Lunch', null, current_date),
('sd', 'Screen Door Pearl District', 'food', 'Pearl District', -122.6827051, 45.523796, 4.6, 'Brunch & dinner daily', 'Southern · Fried chicken', '🍗', 'A Pearl District favorite for Southern fried chicken and biscuits, especially at brunch.', 'Dinner', null, current_date)
on conflict (id) do update set
  name = excluded.name, neighborhood = excluded.neighborhood, lng = excluded.lng, lat = excluded.lat,
  rating = excluded.rating, hours = excluded.hours, specialty = excluded.specialty, photo = excluded.photo,
  description = excluded.description, meal = excluded.meal, last_verified_on = excluded.last_verified_on;
